"""Agent gateway (WP-05) — the provider-agnostic LLM seam and its local contracts.

The agent gateway is where the system will, in future work packages, turn an
explicit prompt into a structured, validated model response without letting the
LLM write domain state directly.  WP-05a / T-05-01 delivers only the foundation:
a small provider-agnostic :class:`LLMProvider` ``Protocol`` plus deterministic,
serializable request / message / usage / response value shapes, bounded
fail-closed validators, and an offline, deterministic :class:`FakeLLMProvider`
for tests.

Everything here is local, deterministic, and offline: no network, no provider
SDK, no credential/environment access, no real clock, and no content egress.  A
provider call returns inert *data* to the caller; it never writes project state,
events, artifacts, or full-content logs.  The reserved production adapter (a real
network LLM provider reached through an audited tool broker) would implement the
same :class:`LLMProvider` protocol without the gateway changing — mirroring the
reserved ports in :mod:`auto_bioinfo.ports`.

WP-05b / T-05-02 adds the local :class:`PromptRegistry` contract foundation: a
deterministic, offline registry that resolves a prompt only by stable identity
(prompt id + exact version), binds it to a canonical template hash and a target
schema reference, and never silently falls back to unregistered content.

WP-05c / T-05-03 adds the local structured-output admission contract: strict,
fail-closed parsing of an inert provider response into structured data, a bounded
local JSON-schema-subset validator plus an offline :class:`SchemaRegistry`, and
:func:`admit_structured_output`, which binds a response to the prompt's exact
registered target schema (no silent fallback), runs a bounded local repair retry
over an explicit candidate sequence, and returns an inert :class:`AdmissionDecision`
— never writing project state, events, artifacts, or domain tables.

WP-05d / T-05-04 adds the local domain semantic validator hook: an offline
:class:`SemanticValidatorRegistry` plus :class:`SemanticValidationResult` so a
deterministic semantic validator runs after schema admission and before an accepted
object is returned, resolved only by explicit id (no silent fall-back to no-op
validation) and failing closed on an unknown / raising / malformed validator.

WP-05e / T-05-05 adds the local sensitive-content / minimum-context / redaction
contract: a deterministic :func:`classify_field_sensitivity` and a
:func:`build_model_context` that, given a project :class:`ProjectPolicy` (or a policy-
shaped mapping) and an explicit set of candidate fields, classify each requested field
by sensitivity, admit only the policy-allowed tiers, **block every ``sensitive`` field
and withhold every ``unknown`` field**, redact inline secrets from admitted values, and
return an inert :class:`ContextBuildDecision` whose public projection never leaks a raw
sensitive value — all before any model/provider call exists, with no content egress.

WP-05f / T-05-06 adds the local tool allowlist & Tool Broker contract: a
:class:`ToolRegistry` allowlist of admitted tool identities/versions plus a
:class:`ToolBroker` that, given an inert :class:`ToolCallRequest`, checks it fail-closed
against the allowlist (an unknown / disabled / version-mismatched / caller-disallowed
tool is denied), blocks raw sensitive arguments and redacts the rest before any handler
sees them, runs only the registered deterministic in-process handler for an authorized
call, and returns an inert :class:`ToolMediationDecision` carrying a bounded redacted
result — with no real tool / shell / subprocess / network / provider call and no egress.

WP-05g / T-05-07 adds the local restricted raw-output artifact reference contract: a
:class:`RestrictedRawOutputArtifact` that holds an already-returned model response's full
raw output privately and a :func:`build_raw_output_artifact` builder that, from inert
synthetic response data (with an optional :class:`AdmissionDecision` binding), produces a
restricted artifact reference plus business-object-safe and bounded audit projections —
keeping the full raw output reachable **only** through an explicit restricted accessor and
withholding it from every ``to_dict`` / business / audit / repr projection, with no real
provider/tool/network call, no durable storage, and no content egress.

Later T-05 slices (durable raw-output artifact storage, audit/usage/budget machinery) are
out of scope for this foundation.
"""

from __future__ import annotations

from .context_builder import (
    BUILD_CODES,
    CODE_MALFORMED_FIELDS,
    CODE_MALFORMED_POLICY,
    CODE_MALFORMED_REQUEST,
    CODE_MISSING_POLICY,
    CODE_POLICY_DISALLOWED,
    CODE_SENSITIVE_BLOCKED,
    CODE_TOO_MANY_FIELDS,
    CODE_UNKNOWN_FIELD,
    CODE_UNKNOWN_SENSITIVITY,
    DECLARABLE_SENSITIVITIES,
    FIELD_CODES,
    MAX_CONTEXT_FIELDS,
    MAX_FIELD_NAME_LENGTH,
    MAX_VALUE_SCAN_DEPTH,
    POLICY_EGRESS_TIERS,
    SENSITIVITIES,
    SENSITIVITY_INTERNAL,
    SENSITIVITY_PUBLIC,
    SENSITIVITY_SENSITIVE,
    SENSITIVITY_UNKNOWN,
    STATUS_BLOCKED,
    STATUS_BUILT,
    ContextBuildDecision,
    ContextFieldOutcome,
    build_model_context,
    classify_field_sensitivity,
)
from .context_builder import REASON_CODES as CONTEXT_BUILDER_REASON_CODES
from .context_builder import STATUSES as CONTEXT_BUILD_STATUSES
from .llm_provider import (
    CODE_CONTENT_TOO_LONG,
    CODE_EMPTY_MESSAGES,
    CODE_FORBIDDEN_METADATA,
    CODE_MALFORMED_CONTENT,
    CODE_MALFORMED_FINISH_REASON,
    CODE_MALFORMED_MAX_TOKENS,
    CODE_MALFORMED_MESSAGES,
    CODE_MALFORMED_METADATA,
    CODE_MALFORMED_MODEL,
    CODE_MALFORMED_PROVIDER,
    CODE_MALFORMED_RESPONSE,
    CODE_MALFORMED_ROLE,
    CODE_MALFORMED_STOP,
    CODE_MALFORMED_TEMPERATURE,
    CODE_MALFORMED_USAGE,
    CODE_NEGATIVE_TOKENS,
    CODE_TOKENS_TOO_LARGE,
    CODE_TOO_MANY_MESSAGES,
    CODE_USAGE_INCONSISTENT,
    FINISH_CONTENT_FILTER,
    FINISH_ERROR,
    FINISH_LENGTH,
    FINISH_REASONS,
    FINISH_STOP,
    FORBIDDEN_METADATA_KEY_MARKERS,
    REASON_CODES,
    REQUEST_CODES,
    RESPONSE_CODES,
    ROLE_ASSISTANT,
    ROLE_SYSTEM,
    ROLE_USER,
    ROLES,
    USAGE_CODES,
    FakeLLMProvider,
    LLMContractError,
    LLMMessage,
    LLMProvider,
    LLMRequest,
    LLMResponse,
    LLMUsage,
    ensure_valid_request,
    ensure_valid_response,
    validate_message,
    validate_request,
    validate_response,
    validate_usage,
)
from .prompt_registry import (
    CODE_DUPLICATE_REGISTRATION,
    CODE_EMPTY_TEMPLATE,
    CODE_HASH_MISMATCH,
    CODE_MALFORMED_PROMPT_ID,
    CODE_MALFORMED_RECORD,
    CODE_MALFORMED_TARGET_SCHEMA,
    CODE_MALFORMED_VERSION,
    CODE_TEMPLATE_TOO_LONG,
    CODE_UNKNOWN_PROMPT,
    CODE_UNKNOWN_VERSION,
    MAX_PROMPT_ID_LENGTH,
    MAX_TARGET_SCHEMA_ID_LENGTH,
    MAX_TEMPLATE_LENGTH,
    MAX_VERSION_LENGTH,
    RECORD_CODES,
    REGISTRY_CODES,
    PromptRegistry,
    PromptRegistryError,
    RegisteredPrompt,
    ensure_valid_prompt,
    validate_prompt,
)
from .prompt_registry import REASON_CODES as PROMPT_REASON_CODES
from .raw_output_artifact import (
    ACCESS_TIER_AUDIT_ONLY,
    ACCESS_TIER_RESTRICTED_STORE,
    ACCESS_TIERS,
    BINDING_CODES,
    CODE_EMPTY_RAW_OUTPUT,
    CODE_MALFORMED_BINDING,
    CODE_MALFORMED_RAW_OUTPUT,
    CODE_MALFORMED_RESTRICTION,
    CODE_MISSING_BINDING,
    CODE_MISSING_PARSED_REF,
    CODE_NONSERIALIZABLE_RAW_OUTPUT,
    CODE_RAW_OUTPUT_LEAK,
    CODE_RAW_OUTPUT_TOO_LARGE,
    MAX_LABEL_LENGTH,
    MAX_RAW_OUTPUT_BYTES,
    MAX_REFERENCE_LENGTH,
    RAW_OUTPUT_CODES,
    REDACTION_NOT_REDACTED,
    REDACTION_REDACTED,
    REDACTION_STATUSES,
    RESTRICTION_HIGHLY_RESTRICTED,
    RESTRICTION_LABELS,
    RESTRICTION_RESTRICTED,
    RETENTION_EPHEMERAL,
    RETENTION_EXTENDED,
    RETENTION_HINTS,
    RETENTION_SHORT,
    RETENTION_STANDARD,
    RawOutputArtifactDecision,
    RestrictedRawOutputArtifact,
    build_raw_output_artifact,
)
from .raw_output_artifact import CODE_MALFORMED_RESPONSE as CODE_RAWART_MALFORMED_RESPONSE
from .raw_output_artifact import MAX_PAYLOAD_DEPTH as MAX_RAWART_PAYLOAD_DEPTH
from .raw_output_artifact import REASON_CODES as RAW_OUTPUT_ARTIFACT_REASON_CODES
from .raw_output_artifact import STATUS_BUILT as RAWART_STATUS_BUILT
from .raw_output_artifact import STATUS_REJECTED as RAWART_STATUS_REJECTED
from .raw_output_artifact import STATUSES as RAW_OUTPUT_ARTIFACT_STATUSES
from .structured_output import (
    ADMISSION_CODES,
    CODE_DUPLICATE_SCHEMA,
    CODE_DUPLICATE_VALIDATOR,
    CODE_EMPTY_PAYLOAD,
    CODE_MALFORMED_JSON,
    CODE_MALFORMED_MAX_ATTEMPTS,
    CODE_MALFORMED_SCHEMA,
    CODE_MALFORMED_SCHEMA_ID,
    CODE_MALFORMED_VALIDATOR,
    CODE_MALFORMED_VALIDATOR_ID,
    CODE_MALFORMED_VALIDATOR_REQUEST,
    CODE_MALFORMED_VALIDATOR_RESULT,
    CODE_MULTIPLE_PAYLOADS,
    CODE_NO_CANDIDATES,
    CODE_NON_FINITE_NUMBER,
    CODE_PAYLOAD_TOO_LARGE,
    CODE_REPAIR_EXHAUSTED,
    CODE_SCHEMA_DRIFT,
    CODE_SCHEMA_MISMATCH,
    CODE_SCHEMA_VIOLATION,
    CODE_SEMANTIC_REJECTED,
    CODE_SEMANTIC_VALIDATOR_ERROR,
    CODE_UNKNOWN_SCHEMA,
    CODE_UNKNOWN_VALIDATOR,
    CODE_UNSUPPORTED_SHAPE,
    DEFAULT_MAX_ATTEMPTS,
    MAX_OUTPUT_TEXT_LENGTH,
    MAX_REPAIR_ATTEMPTS,
    MAX_SCHEMA_ID_LENGTH,
    MAX_SEMANTIC_VALIDATORS,
    MAX_VALIDATION_DEPTH,
    MAX_VALIDATOR_ID_LENGTH,
    PARSE_CODES,
    REPAIRABLE_CODES,
    SCHEMA_CODES,
    SCHEMA_TYPES,
    SEMANTIC_CODES,
    STATUS_ACCEPTED,
    STATUS_REJECTED,
    STATUSES,
    SUPPORTED_SCHEMA_KEYWORDS,
    VALIDATOR_REGISTRY_CODES,
    AdmissionAttempt,
    AdmissionDecision,
    SchemaRegistry,
    SemanticValidationResult,
    SemanticValidatorRegistry,
    StructuredOutputError,
    admit_structured_output,
    is_repairable,
    parse_structured_output,
    validate_instance,
    validate_schema_definition,
)
from .structured_output import CODE_MALFORMED_RESPONSE as CODE_ADMIT_MALFORMED_RESPONSE
from .structured_output import REASON_CODES as STRUCTURED_OUTPUT_REASON_CODES
from .tool_broker import (
    ALLOWLIST_CODES,
    CODE_ARGUMENTS_TOO_LARGE,
    CODE_CALLER_NOT_ALLOWED,
    CODE_DUPLICATE_TOOL,
    CODE_HANDLER_ERROR,
    CODE_MALFORMED_ALLOWED_CALLERS,
    CODE_MALFORMED_ARGUMENTS,
    CODE_MALFORMED_HANDLER,
    CODE_MALFORMED_IDENTITY,
    CODE_MALFORMED_RESULT,
    CODE_MALFORMED_TOOL_ID,
    CODE_MALFORMED_TOOL_VERSIONS,
    CODE_NON_PUBLIC_ARGUMENT,
    CODE_NONSERIALIZABLE_ARGUMENTS,
    CODE_RESULT_TOO_LARGE,
    CODE_SENSITIVE_ARGUMENT,
    CODE_TOO_MANY_ARGUMENTS,
    CODE_TOOL_DISABLED,
    CODE_UNKNOWN_TOOL,
    CODE_VERSION_MISMATCH,
    EXECUTION_CODES,
    MAX_ALLOWED_CALLERS,
    MAX_ARG_NAME_LENGTH,
    MAX_ARGUMENTS_BYTES,
    MAX_CALLER_ID_LENGTH,
    MAX_PAYLOAD_DEPTH,
    MAX_PROJECT_REF_LENGTH,
    MAX_RESULT_BYTES,
    MAX_TOOL_ARGUMENTS,
    MAX_TOOL_ID_LENGTH,
    MAX_TOOL_VERSION_LENGTH,
    MAX_TOOL_VERSIONS,
    STATUS_ALLOWED,
    STATUS_DENIED,
    ToolBroker,
    ToolBrokerError,
    ToolCallRequest,
    ToolMediationDecision,
    ToolRegistry,
    ToolSpec,
)
from .tool_broker import CODE_MALFORMED_REQUEST as CODE_TOOL_MALFORMED_REQUEST
from .tool_broker import REASON_CODES as TOOL_BROKER_REASON_CODES
from .tool_broker import REGISTRY_CODES as TOOL_REGISTRY_CODES
from .tool_broker import REQUEST_CODES as TOOL_REQUEST_CODES
from .tool_broker import STATUSES as TOOL_BROKER_STATUSES

__all__ = [
    "CODE_CONTENT_TOO_LONG",
    "CODE_EMPTY_MESSAGES",
    "CODE_FORBIDDEN_METADATA",
    "CODE_MALFORMED_CONTENT",
    "CODE_MALFORMED_FINISH_REASON",
    "CODE_MALFORMED_MAX_TOKENS",
    "CODE_MALFORMED_MESSAGES",
    "CODE_MALFORMED_METADATA",
    "CODE_MALFORMED_MODEL",
    "CODE_MALFORMED_PROVIDER",
    "CODE_MALFORMED_RESPONSE",
    "CODE_MALFORMED_ROLE",
    "CODE_MALFORMED_STOP",
    "CODE_MALFORMED_TEMPERATURE",
    "CODE_MALFORMED_USAGE",
    "CODE_NEGATIVE_TOKENS",
    "CODE_TOKENS_TOO_LARGE",
    "CODE_TOO_MANY_MESSAGES",
    "CODE_USAGE_INCONSISTENT",
    "FINISH_CONTENT_FILTER",
    "FINISH_ERROR",
    "FINISH_LENGTH",
    "FINISH_REASONS",
    "FINISH_STOP",
    "FORBIDDEN_METADATA_KEY_MARKERS",
    "REASON_CODES",
    "REQUEST_CODES",
    "RESPONSE_CODES",
    "ROLE_ASSISTANT",
    "ROLE_SYSTEM",
    "ROLE_USER",
    "ROLES",
    "USAGE_CODES",
    "FakeLLMProvider",
    "LLMContractError",
    "LLMMessage",
    "LLMProvider",
    "LLMRequest",
    "LLMResponse",
    "LLMUsage",
    "ensure_valid_request",
    "ensure_valid_response",
    "validate_message",
    "validate_request",
    "validate_response",
    "validate_usage",
    "CODE_DUPLICATE_REGISTRATION",
    "CODE_EMPTY_TEMPLATE",
    "CODE_HASH_MISMATCH",
    "CODE_MALFORMED_PROMPT_ID",
    "CODE_MALFORMED_RECORD",
    "CODE_MALFORMED_TARGET_SCHEMA",
    "CODE_MALFORMED_VERSION",
    "CODE_TEMPLATE_TOO_LONG",
    "CODE_UNKNOWN_PROMPT",
    "CODE_UNKNOWN_VERSION",
    "MAX_PROMPT_ID_LENGTH",
    "MAX_TARGET_SCHEMA_ID_LENGTH",
    "MAX_TEMPLATE_LENGTH",
    "MAX_VERSION_LENGTH",
    "RECORD_CODES",
    "REGISTRY_CODES",
    "PROMPT_REASON_CODES",
    "PromptRegistry",
    "PromptRegistryError",
    "RegisteredPrompt",
    "ensure_valid_prompt",
    "validate_prompt",
    "ADMISSION_CODES",
    "CODE_DUPLICATE_SCHEMA",
    "CODE_DUPLICATE_VALIDATOR",
    "CODE_EMPTY_PAYLOAD",
    "CODE_MALFORMED_JSON",
    "CODE_MALFORMED_MAX_ATTEMPTS",
    "CODE_ADMIT_MALFORMED_RESPONSE",
    "CODE_MALFORMED_SCHEMA",
    "CODE_MALFORMED_SCHEMA_ID",
    "CODE_MALFORMED_VALIDATOR",
    "CODE_MALFORMED_VALIDATOR_ID",
    "CODE_MALFORMED_VALIDATOR_REQUEST",
    "CODE_MALFORMED_VALIDATOR_RESULT",
    "CODE_MULTIPLE_PAYLOADS",
    "CODE_NO_CANDIDATES",
    "CODE_NON_FINITE_NUMBER",
    "CODE_PAYLOAD_TOO_LARGE",
    "CODE_REPAIR_EXHAUSTED",
    "CODE_SCHEMA_DRIFT",
    "CODE_SCHEMA_MISMATCH",
    "CODE_SCHEMA_VIOLATION",
    "CODE_SEMANTIC_REJECTED",
    "CODE_SEMANTIC_VALIDATOR_ERROR",
    "CODE_UNKNOWN_SCHEMA",
    "CODE_UNKNOWN_VALIDATOR",
    "CODE_UNSUPPORTED_SHAPE",
    "DEFAULT_MAX_ATTEMPTS",
    "MAX_OUTPUT_TEXT_LENGTH",
    "MAX_REPAIR_ATTEMPTS",
    "MAX_SCHEMA_ID_LENGTH",
    "MAX_SEMANTIC_VALIDATORS",
    "MAX_VALIDATION_DEPTH",
    "MAX_VALIDATOR_ID_LENGTH",
    "PARSE_CODES",
    "REPAIRABLE_CODES",
    "SCHEMA_CODES",
    "SCHEMA_TYPES",
    "SEMANTIC_CODES",
    "STATUS_ACCEPTED",
    "STATUS_REJECTED",
    "STATUSES",
    "SUPPORTED_SCHEMA_KEYWORDS",
    "VALIDATOR_REGISTRY_CODES",
    "STRUCTURED_OUTPUT_REASON_CODES",
    "AdmissionAttempt",
    "AdmissionDecision",
    "SchemaRegistry",
    "SemanticValidationResult",
    "SemanticValidatorRegistry",
    "StructuredOutputError",
    "admit_structured_output",
    "is_repairable",
    "parse_structured_output",
    "validate_instance",
    "validate_schema_definition",
    "BUILD_CODES",
    "CODE_MALFORMED_FIELDS",
    "CODE_MALFORMED_POLICY",
    "CODE_MALFORMED_REQUEST",
    "CODE_MISSING_POLICY",
    "CODE_POLICY_DISALLOWED",
    "CODE_SENSITIVE_BLOCKED",
    "CODE_TOO_MANY_FIELDS",
    "CODE_UNKNOWN_FIELD",
    "CODE_UNKNOWN_SENSITIVITY",
    "CONTEXT_BUILDER_REASON_CODES",
    "CONTEXT_BUILD_STATUSES",
    "DECLARABLE_SENSITIVITIES",
    "FIELD_CODES",
    "MAX_CONTEXT_FIELDS",
    "MAX_FIELD_NAME_LENGTH",
    "MAX_VALUE_SCAN_DEPTH",
    "POLICY_EGRESS_TIERS",
    "SENSITIVITIES",
    "SENSITIVITY_INTERNAL",
    "SENSITIVITY_PUBLIC",
    "SENSITIVITY_SENSITIVE",
    "SENSITIVITY_UNKNOWN",
    "STATUS_BLOCKED",
    "STATUS_BUILT",
    "ContextBuildDecision",
    "ContextFieldOutcome",
    "build_model_context",
    "classify_field_sensitivity",
    "MAX_TOOL_ID_LENGTH",
    "MAX_TOOL_VERSION_LENGTH",
    "MAX_CALLER_ID_LENGTH",
    "MAX_PROJECT_REF_LENGTH",
    "MAX_TOOL_VERSIONS",
    "MAX_ALLOWED_CALLERS",
    "MAX_TOOL_ARGUMENTS",
    "MAX_ARG_NAME_LENGTH",
    "MAX_PAYLOAD_DEPTH",
    "MAX_ARGUMENTS_BYTES",
    "MAX_RESULT_BYTES",
    "STATUS_ALLOWED",
    "STATUS_DENIED",
    "TOOL_BROKER_STATUSES",
    "CODE_TOOL_MALFORMED_REQUEST",
    "CODE_MALFORMED_IDENTITY",
    "CODE_MALFORMED_ARGUMENTS",
    "CODE_TOO_MANY_ARGUMENTS",
    "CODE_ARGUMENTS_TOO_LARGE",
    "CODE_NONSERIALIZABLE_ARGUMENTS",
    "CODE_SENSITIVE_ARGUMENT",
    "CODE_NON_PUBLIC_ARGUMENT",
    "CODE_UNKNOWN_TOOL",
    "CODE_TOOL_DISABLED",
    "CODE_VERSION_MISMATCH",
    "CODE_CALLER_NOT_ALLOWED",
    "CODE_HANDLER_ERROR",
    "CODE_MALFORMED_RESULT",
    "CODE_RESULT_TOO_LARGE",
    "TOOL_REQUEST_CODES",
    "ALLOWLIST_CODES",
    "EXECUTION_CODES",
    "TOOL_BROKER_REASON_CODES",
    "CODE_MALFORMED_TOOL_ID",
    "CODE_MALFORMED_TOOL_VERSIONS",
    "CODE_MALFORMED_ALLOWED_CALLERS",
    "CODE_MALFORMED_HANDLER",
    "CODE_DUPLICATE_TOOL",
    "TOOL_REGISTRY_CODES",
    "ToolBrokerError",
    "ToolSpec",
    "ToolRegistry",
    "ToolCallRequest",
    "ToolMediationDecision",
    "ToolBroker",
    "MAX_REFERENCE_LENGTH",
    "MAX_LABEL_LENGTH",
    "MAX_RAWART_PAYLOAD_DEPTH",
    "MAX_RAW_OUTPUT_BYTES",
    "RAWART_STATUS_BUILT",
    "RAWART_STATUS_REJECTED",
    "RAW_OUTPUT_ARTIFACT_STATUSES",
    "RESTRICTION_RESTRICTED",
    "RESTRICTION_HIGHLY_RESTRICTED",
    "RESTRICTION_LABELS",
    "ACCESS_TIER_RESTRICTED_STORE",
    "ACCESS_TIER_AUDIT_ONLY",
    "ACCESS_TIERS",
    "RETENTION_EPHEMERAL",
    "RETENTION_SHORT",
    "RETENTION_STANDARD",
    "RETENTION_EXTENDED",
    "RETENTION_HINTS",
    "REDACTION_REDACTED",
    "REDACTION_NOT_REDACTED",
    "REDACTION_STATUSES",
    "CODE_RAWART_MALFORMED_RESPONSE",
    "CODE_MISSING_BINDING",
    "CODE_MALFORMED_BINDING",
    "CODE_MISSING_PARSED_REF",
    "CODE_MALFORMED_RESTRICTION",
    "CODE_EMPTY_RAW_OUTPUT",
    "CODE_RAW_OUTPUT_TOO_LARGE",
    "CODE_NONSERIALIZABLE_RAW_OUTPUT",
    "CODE_MALFORMED_RAW_OUTPUT",
    "CODE_RAW_OUTPUT_LEAK",
    "BINDING_CODES",
    "RAW_OUTPUT_CODES",
    "RAW_OUTPUT_ARTIFACT_REASON_CODES",
    "RestrictedRawOutputArtifact",
    "RawOutputArtifactDecision",
    "build_raw_output_artifact",
]
